stages:
  - build
  - deploy

build:
  stage: build
  image: node:20.10.0
  script:
    - npm install
    - npm run
    - docker build -t individual-front-end .

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    - docker pull individual-front-end
    - docker stop individual-front-end-staging
    - docker rm individual-front-end-staging
    - docker run -d -p 5173:5173 --name=individual-front-end-staging individual-front-end
