stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_NAME: individual-front-end

build:
  stage: build
  image: node:20.10.0
  script:
    - npm install
    - npm run
    - docker build -t $DOCKER_IMAGE_NAME .

cache:
  key: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  paths:
    - node_modules/

test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  script:
    - cd C:\School\S3-Individual\individual-frontend
    - npm ci
    - Start-Job -ScriptBlock { npm start }
    - Start-Sleep -Seconds 10 # Give time for the server to initialize
    - npm run e2e

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE_NAME
    - docker stop individual-front-end-staging || true
    - docker rm individual-front-end-staging || true
    - docker run -d -p 5173:5173 --name=individual-front-end-staging $DOCKER_IMAGE_NAME
