variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
    - ls
    - pwd

test:
  stage: test
  script:
    - ls
    - pwd
    - ./gradlew test

